let state =  {
  recommendations: [
    {
      user: "Pierre",
      text:
        "I love how Jon Krakauer shows all the different perspectives about the perilous year in Everest. Full of adventure but also heartbreak.",
      ISBN: "9780679462712",
      tags: ["Adventure"],
    },
    {
      user: "Pierre",
      text:
        "This book is a heartwrenching look at how racism was institutionalized at a real alternative school for boys in Florida.",
      ISBN: "9780385537087",
      tags: ["Black Lives Matter", "Cruelty"],
    },
    {
      user: "Pierre",
      text:
        "Despite not normally being a fan of fantasy, I loved the friendship between Harry, Ron, and Hermione.",
      ISBN: "9781781100509",
      tags: ["Friendship"],
    },
    {
      user: "Pierre",
      text:
        "George Saunders is a master of experimentation. All these stories differ widly, but every character faces decisions that affect their future in major ways.",
      ISBN: "9780812993813",
      tags: ["Decisions"],
    },
  ],
  searchTerm: "",
  currentTags: [],
  tagList: [
    "Adventure",
    "Belief",
    "Forgiveness",
    "Decisions",
    "Death & Dying",
    "Love",
    "Acceptance",
    "Courage",
    "Change",
    "Empathy",
    "Overcoming Adversity",
    "Pressure",
    "Friendship",
    "Sacrifice",
    "The Bonds of Family",
    "Suffering",
    "Conflict",
    "Abandonment",
    "Alienation",
    "Ambition",
    "Coming of Age",
    "Freedom",
    "Gender",
    "Justice",
    "Isolation",
    "Cruelty",
    "Fate",
    "Hope",
    "Guilt",
    "Black Lives Matter",
    "LGBTQ Pride",
  ],
};
